PS C:\Users\OM\smart-cake-ordering-platform> Get-Content .\PaymentService\PaymentService\src\main\resources\application.properties                                      
spring.application.name=payment-service
server.port=8085

# ===============================
# MYSQL
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/smart_cake_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# EUREKA
# ===============================

eureka.client.service-url.defaultZone=http://localhost:3030/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# ===============================
# RAZORPAY
# ===============================

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}


# ===============================
# KAFKA
# ===============================

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
