spring.application.name=user-service
server.port=8081

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/smart_cake_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=https://smart-cake-ordering-platform-2.onrender.com/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true