spring.application.name=ApiGateway
server.port=${PORT:8080}


# ===============================
# EUREKA CLIENT
# ===============================

eureka.client.service-url.defaultZone=https://smart-cake-ordering-platform-2.onrender.com/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# ===============================
# CORS
# ===============================

spring.web.cors.allowed-origins=https://cakeon-web-eight.vercel.app
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true


# ===============================
# JWT
# ===============================

jwt.secret=${JWT_SECRET}


# ===============================
# GATEWAY ROUTES - WEBMVC
# ===============================


# ===============================
# USER SERVICE
# ===============================

spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/users/**


# ===============================
# AUTH SERVICE
# ===============================

spring.cloud.gateway.server.webmvc.routes[1].id=auth-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/auth/**


# ===============================
# CAKE SERVICE
# ===============================

spring.cloud.gateway.server.webmvc.routes[2].id=cake-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://CakeService
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/cakes/**


# ===============================
# ORDER SERVICE
# ===============================

spring.cloud.gateway.server.webmvc.routes[3].id=order-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://OrderService
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/orders/**


# ===============================
# DELIVERY SERVICE
# ===============================

spring.cloud.gateway.server.webmvc.routes[4].id=delivery-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://deliveryService
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/deliveries/**


# ===============================
# REVIEW SERVICE
# ===============================

spring.cloud.gateway.server.webmvc.routes[5].id=review-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://OrderService
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/reviews/**


# ===============================
# ADMIN SERVICE
# ===============================

spring.cloud.gateway.server.webmvc.routes[6].id=admin-service
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/admin/**


# ===============================
# CART SERVICE
# ===============================

spring.cloud.gateway.server.webmvc.routes[7].id=cart-service
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://OrderService
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/cart/**


# ===============================
# PAYMENT SERVICE
# ===============================

spring.cloud.gateway.server.webmvc.routes[8].id=payment-service
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://payment-service
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/payments/**